### ISSUE TITLE
Integration won't initialize?

### ISSUE THREAD

**Issue by ChrisWarwick** [ryanbdclark/ripple_energy#1]
Hi,

This looks great, but I struggling to get it to initialize? Running latest HASS (2024.02.01). Integration installs OK and asks for API key - but then keeps saying "Failed Initialization - will retry".

I've deleted/reinstalled. Generated a new Ripple API key. 

Anything else I can try?

Thanks.

**Comment by ryanbdclark** [comment]
Have you got a reservation with ripple for a project that hasn’t completed yet? I believe there is an issue when this is the case that I need to fix.

**Comment by ChrisWarwick** [comment]
Hi - yes, I have Graig Fatha (active) and Kirk Hill (pending)

Very happy to help with testing :-) 

Thanks

**Comment by ryanbdclark** [comment]
I've just released version 2024.2.1 please can you update to this version and try again. This should fix the issue however I'm only invested in Graig Fatha so can't confirm myself.

**Comment by ChrisWarwick** [comment]
Thanks Ryan - all working :-)

I updated/restarted HA, added the integration and entered my API key. I got a "Device already configured" message, but this was because the integration was actually already there from my last attempt (I'd just disabled it). I re-enabled and all is good.

Thanks again 👍

**Comment by ryanbdclark** [comment]
Great thanks for confirming 😊
