### ISSUE TITLE
Is it possible to assign the "£" unit to the financial numbers? Also Current Savings discussion.

### ISSUE THREAD

**Issue by Ironrampant** [ryanbdclark/ripple_energy#10]
Is it possible to assign the "£" unit to the financial numbers?  I saw that the items have the £ in the name eg "£ Earned Last Month" but I was wondering if there was an issue assigning the unit of measurement in the integration.

Failing that, I think that the "Current Savings" item needs to be labelled with a £ for consistency eg "£ Current Savings"

"Current Savings" is a rate but is it savings/hour?

All other financials are described as "Earnings" while this one is "Savings".  Would "£ Current Hourly Earn Rate" be more accurate?

![Screenshot 2024-08-15 071718](https://github.com/user-attachments/assets/b2df1564-cd4b-40aa-ad58-d11af6c5a031)

**Comment by ryanbdclark** [comment]
The newest release 2024.8.1 now has the units of savings as 'GBP'

The current savings isn't savings/hour as far as I'm aware it's just the estimated savings for the last 30 minutes.
