### ISSUE TITLE
Earned today stopped updating

### ISSUE THREAD

**Issue by CymruDad78** [ryanbdclark/ripple_energy#14]
Hi,
I’m fairly new to HA, so still learning. I had the Ripple intergration working well, but the Earned Today (for Kirk Hill), seemed to stop working a few days ago. 

I know there will be some days where nothing is earned if conditions are calm, but it seems to have been at zero since 29th August.

Any suggestions? The other entities seem to be updating ok.
![IMG_2332](https://github.com/user-attachments/assets/fa6f9fae-5253-4310-b4f3-f868c2d268f9)
![IMG_2331](https://github.com/user-attachments/assets/9da189ce-92c5-4b17-a538-045d243f6a20)

**Comment by Alibloke** [comment]
It's broken at Ripple's end:
![457476361_10160491772788152_7347776853630879471_n](https://github.com/user-attachments/assets/1c332106-746e-48eb-b622-8abd51158c20)

**Comment by CymruDad78** [comment]
> It's broken at Ripple's end: ![457476361_10160491772788152_7347776853630879471_n](https://private-user-images.githubusercontent.com/773816/363958143-1c332106-746e-48eb-b622-8abd51158c20.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNjMzNDcsIm5iZiI6MTcyNTM2MzA0NywicGF0aCI6Ii83NzM4MTYvMzYzOTU4MTQzLTFjMzMyMTA2LTc0NmUtNDhlYi1iNjIyLThhYmQ1MTE1OGMyMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QxMTMwNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDM0NzI3ZDQxNTAxMTBhMzdlN2U1N2Q2YTg3NGNmZGM3YTJiNjRhMzA1MjQ2M2U5NzE2OTUyMDdkOGU4MjQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0s5PQMD6yhRS7Csx6ZxTomPKoh_2KyiMC8-kFiNS4_Y)

Ah ok, hadn’t spotted that. Thanks 👍
