### ISSUE TITLE
Unknown error occured / Invalid API Key

### ISSUE THREAD

**Issue by c4weddell** [ryanbdclark/ripple_energy#2]
The integration now initialises, but when I enter my API key I get 'Unknown error occured', and checking the logs it would appear to be an "Invalid API Key" error...

Traceback (most recent call last):
  File "/config/custom_components/ripple_energy/config_flow.py", line 59, in async_step_user
    data = await ripple_api.request(assets=ASSETS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyrippleapi/api.py", line 90, in request
    raise RippleAuthenticationError("Invalid API Key")
pyrippleapi.exceptions.RippleAuthenticationError: Invalid API Key

I am all up to date with updates, running the latest versions of everything.  In my Ripple Energy dashboard when I "Follow this link for access to your generation data via the REST API" I can see data (though I presume it is failing before it gets any data.

**Comment by ryanbdclark** [comment]
That's odd, I'm able to remove the integration completely and set up with my own API key without issues. It's failing at the point it's trying to retrieve data. The Ripple API is incredibly simply and only really has one endpoint.

Are you able to ensure that the API you are using is definitely correct, and if still not working try and generate a new API key on the ripple website?

If it's still not working after this I may need you to provide me with your API key in a secure way as I cannot replicate this issue.

**Comment by c4weddell** [comment]
I generated a new API key, after also removing and reinstalling the integration, and it is now working for me.
