### ISSUE TITLE
Failed Setup.

### ISSUE THREAD

**Issue by thevilla** [ryanbdclark/ripple_energy#3]
This error originated from a custom integration.

Logger: custom_components.ripple_energy.coordinator
Source: helpers/update_coordinator.py:315
integration: Ripple Energy
First occurred: 17:22:29 (12 occurrences)
Last logged: 17:27:44

Hi,
I found this integration for HA and very grateful for it.  Unfortunately it's not working for me.  I'm guessing the API have been modified since this release?
I'm a member of Kirk Hill and Derril Water if that info is any help.

Unexpected error fetching Kirk Hill data: 'timestamp'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ripple_energy/coordinator.py", line 43, in _async_update_data
    await self.asset.update_data()
  File "/usr/local/lib/python3.12/site-packages/pyrippleapi/generation_asset.py", line 175, in update_data
    await self.get_telemetry(generation_data["generation"])
  File "/usr/local/lib/python3.12/site-packages/pyrippleapi/generation_asset.py", line 122, in get_telemetry
    self._latest_telemetry["timestamp"],
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'timestamp'

**Comment by ryanbdclark** [comment]
What version of this integration are you using? I believe that version 2024.2.1 fixes this? Let me know if this is the version you are already using

**Comment by thevilla** [comment]
Yes, looks like that is the version I have.

![image](https://github.com/ryanbdclark/ripple_energy/assets/108428343/462d235b-0cb5-4768-a650-c65969b7fbce)

**Comment by ryanbdclark** [comment]
The screenshot is just showing the latest version available rather than what's installed. I assume if you found this integration recently so you are probably on the latest version.

I will need some information from you to help fix this:

Can you check this file on your homeassistant installation

/homeassistant/custom_components/ripple_energy/manifest.json

The last value in the JSON in the version you currently have installed.

If the version is 2024.2.1 then can you please check what's in this file

/homeassistant/custom_components/ripple_energy/const.py

The last value is a list which contains all the supported Ripple assets, it should just be `ASSETS = ["Graig Fatha"]`

As above the integration only supports Graig Fatha currently for a couple of reasons, it's currently the only operational asset from Ripple, and this is the only project I'm invested in so I don't have access to see what the API response for Kirk Hill and others look like.

I'm happy to add support for Kirk Hill etc if you are able to provide me the API response you get from ripple. You can do this by following the below steps, I just need a dump of the information contained in the "generation_assets" array.

`Get your Ripple API key

Login to your Ripple Dashboard

In a new tab, paste in https://rippleenergy.com/rest/member_data/

Back in your Ripple Dashboard, click on the word Energy at the bottom left of the screen, this will copy your API key to your clipboard

Return to the other tab and paste in your API key after member_data/`

**Comment by thevilla** [comment]
Ah, sorry. I didn't realise there wasn't support for anything other than Graig Fatha.  Makes sense.  I just found your work on github and gave it a go!

If you're happy to add support for the projects I'm a member of then I'm happy to help.  See the output below and let me know if you want me to test anything.  Both projects only provide the basic initial data at present but obviously Kirk Hill should be imminent.
Let me know if I can help further.

![image](https://github.com/ryanbdclark/ripple_energy/assets/108428343/03a990f2-692e-4481-8fcb-4a2974da591a)
![image](https://github.com/ryanbdclark/ripple_energy/assets/108428343/e6c77ede-ff33-471b-92f1-dd4505b2d104)
[Ripple output.json](https://github.com/ryanbdclark/ripple_energy/files/14944152/Ripple.output.json)

**Comment by DavidqStokes** [comment]
> Reference

Hi Ryan,

Thanks also for the work on this HA integration. I'm also a Ripple member waiting for Kirk Hill to come online and I installed this integration over the weekend. As I expected at the moment there were no devices or entities are appearing as yet, but I've just read through this issue and see that you need details of the Kirk Hill generation assets array before you can add support.

I think that this will include what you need:

"generation_assets": [{"name": "Kirk Hill", "type": "Windfarm", "status": "N/A", "total_capacity": 18.8, "total_capacity_units": "MW", "member_capacity": 1512.957, "member_capacity_units": "W", "member_expected_annual_generation": 4.8, "member_expected_annual_generation_units": "MWh", "generation": {"generation_unit": "kWh", "latest_telemetry": {}, "latest": {}, "today": {"from": "2024-05-13T00:00:00Z", "to": "2024-05-13T10:47:35.149Z", "contains_estimate": false, "generated": 0.0, "earned": 0.0}, "yesterday": {"from": "2024-05-12T00:00:00Z", "to": "2024-05-13T00:00:00Z", "contains_estimate": false, "generated": 0.0, "earned": 0.0}, "this_week": {"from": "2024-05-13T00:00:00Z", "to": "2024-05-13T10:47:35.149Z", "contains_estimate": false, "generated": 0.0, "earned": 0.0}, "last_week": {"from": "2024-05-06T00:00:00Z", "to": "2024-05-13T00:00:00Z", "contains_estimate": false, "generated": 0.0, "earned": 0.0}, "this_month": {"from": "2024-05-01T00:00:00Z", "to": "2024-05-13T10:47:35.149Z", "contains_estimate": false, "generated": 0.0, "earned": 0.0}, "last_month": {"from": "2024-04-01T00:00:00Z", "to": "2024-05-01T00:00:00Z", "contains_estimate": false, "generated": 0.0, "earned": 0.0}, "this_year": {"from": "2024-01-01T00:00:00Z", "to": "2024-05-13T10:47:35.149Z", "contains_estimate": false, "generated": 0.0, "earned": 0.0}, "last_year": {"from": "2023-01-01T00:00:00Z", "to": "2024-01-01T00:00:00Z", "contains_estimate": false, "generated": 0.0, "earned": 0.0}, "total": {"from": "2000-01-01T00:00:00Z", "to": "2024-05-13T10:47:35.149Z", "contains_estimate": false, "generated": 0.0, "earned": 0.0}}, "forecast": []}]


Thanks so much for taking this on - I'm sure that there will prove to be a large overlap between Ripple investors and HA users, all of whom will appreciate your work.

**Comment by ryanbdclark** [comment]
Thanks both for the info, this should now be fixed in the new version (2024.5.1). Let me know if still not working.

**Comment by DavidqStokes** [comment]
Hi Ryan,

I pulled the latest version (2014.5.1) and the setup failed, even after removing the previous version from HA, and reinstalling.

The error log is as follows:

This error originated from a custom integration.

Logger: custom_components.ripple_energy.coordinator
Source: helpers/update_coordinator.py:315
integration: Ripple Energy
First occurred: 16:27:35 (7 occurrences)
Last logged: 16:28:31

Unexpected error fetching Kirk Hill data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ripple_energy/coordinator.py", line 43, in _async_update_data
    await self.asset.update_data()
  File "/usr/local/lib/python3.12/site-packages/pyrippleapi/generation_asset.py", line 178, in update_data
    await self.get_generation(generation_data["generation"])
  File "/usr/local/lib/python3.12/site-packages/pyrippleapi/generation_asset.py", line 145, in get_generation
    self._generation_data["latest_earned"] = data["latest"]["estimated_savings"]
                                             ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 'estimated_savings'

**Comment by ryanbdclark** [comment]
I've just pushed another version, 2024.5.2 which should fix this new error, let me know if you can now setup or if you are still getting errors.

**Comment by DavidqStokes** [comment]
2024.5.2 appears to be working fine for me.
1 device and 21 entities (6 of which are disabled by default) have appeared for Kirk Hill.
The data that I'd expect to see is there, but obviously no generation as yet - we'll know more next month.

Thanks very much Ryan!

**Comment by ryanbdclark** [comment]
Great thanks for confirming, you should get another 2 entities once Kirk Hill is operational also.

**Comment by thevilla** [comment]
Looks good to me too.  Thank you for doing this.
