### ISSUE TITLE
Latest Telemetry data missing

### ISSUE THREAD

**Issue by mediaguycouk** [ryanbdclark/ripple_energy#4]
You mentioned on the ripple forum that you only have GF invested, so I'm mostly posting this to give you a json file for the other projects.

Specifically for this, there is a "latest telemetry" section that does not have entities created against them (things like temperature and angles).

Thanks for making this so I didn't have to!
[ripple.json](https://github.com/user-attachments/files/16168339/ripple.json)

**Comment by ryanbdclark** [comment]
Thanks for the suggestion, I have just released a new version (2024.7.2) if you update you should now see the telemetry as sensors.

**Comment by DavidqStokes** [comment]
DOH - I feel so foolish!

I have now downloaded the latest version and have the telemetry.
