### ISSUE TITLE
Add Telemetry Data to Integration (Suggestion)

### ISSUE THREAD

**Issue by DavidqStokes** [ryanbdclark/ripple_energy#6]
I notice from the latest Ripple API documentation that 'real time' telemetry data is also available via the API (half hourly values)

latest_telemetry - Latest half hour asset data
  timestamp - yyyy-mm-dd: hh:mm:ss in UTC
  wind_speed_avg - mph (miles per hour)
  generator_speed_avg - rpm (revolutions per minute)
  blade_angle_avg - degrees
  nacelle_position - degrees
  tower_base_temp_avg - degrees celsius
  ambient_temp_max - degrees celsius

It would be great to have some of these on the HA dashboard. Are there any plans to extent to integration to include this data?

**Comment by mediaguycouk** [comment]
Hi David, 
Have you gone to HACS and taken the latest update? It was added here https://github.com/ryanbdclark/ripple_energy/issues/4 but most of it is disabled, so you may have enable them.
