### ISSUE TITLE
Some mislabelled units

### ISSUE THREAD

**Issue by mediaguycouk** [ryanbdclark/ripple_energy#7]
From looking at the ripple dashboard, I think that the following are slightly mislabelled:

1) [SITE}_current_generation is labelled kWh, but is kW
2) [SITE]_wind_speed is lablled km/h, but appear to be mph

![image](https://github.com/user-attachments/assets/1be05011-ed04-4f6a-881f-c6c96285788f)

**Comment by ryanbdclark** [comment]
I think these are both technically correct. Current generation as per the API has a unit of kWh not sure why the dashboard has a different unit. 

![IMG_7016](https://github.com/user-attachments/assets/5c5c13b4-0a38-4ea2-9030-81927e6650dd)

you can change the wind speed to mph. HA automatically converts the wind speed based on your locale which for UK users will be km/h. You can change the entity to mph though as HA will do the conversion for you. It’s worth noting that the wind speed on the dashboard and the one returned on the api aren’t the same thing. The api wind speed is an average wind speed. For example right now the dashboard for GF says the wind speed is 16mph however the average wind speed in the api is 7.285 (I assume also mph). 

![IMG_7015](https://github.com/user-attachments/assets/6c23aceb-889b-4035-818a-a31df0e5d1af)

**Comment by ghost** [comment]
Current generation should be kW not kWh.

**Comment by ryanbdclark** [comment]
Ripple's documentation states this should be kWh not kW so will stick with that

![image](https://github.com/user-attachments/assets/664d3393-11df-4325-96f1-42a2f7c72ebd)

**Comment by xxpas02** [comment]
The dashboard data is showing the current instantaneous POWER generation and as such it is correctly labelled with a unit of power, which is kilowatts (kW).

The api is returning the amount of ENERGY produced during the most recent half-hour metering period and as such it is also correctly labelled  with a unit of energy, which is kilowatt hours (kWh).

The two numerical values of these parameters should not be the same. The power figure should update much more frequently than the half-hourly updates of the energy figure and the energy figure should be equal to half the average of the power figures over the metering period.

For example, if the power figure updates every minute and is a constant 100kW over the whole half hour metering period, then the average power would be 100kW and the energy produced during the same half hour would be 50kWh. 

Hope that makes sense?

**Comment by mediaguycouk** [comment]
xxpas02, I don't think anyone is disagreeing with you. But the resolution here is that Home Assistant pulls figures from the API. Instead of overriding the Ripple API, we use the details they send us.

If Ripple change their unit to kW, the data in home assistant would also change.

**Comment by xxpas02** [comment]
Yes, I just thought an explanation of why it’s not wrong might help others who come here to raise the same issue that I did :)
