### ISSUE TITLE
Whitelaw Brae

### ISSUE THREAD

**Issue by shirehorse99** [ryanbdclark/ripple_energy#8]
hi Ryan, great job on the integration  - keep up the good work.

should WB be on my account yet - it shows up in API - DW is picked up in your integration but not WB

cheers

**Comment by walderston** [comment]
@shirehorse99 looks like the last build by @ryanbdclark didn't include my PR #5 to add WB.

You can add it yourself by modifying /custom_components/ripple_energy/const.py and adding 'Whitelaw Brae' to the list
i.e. link 5 should look like `ASSETS = ["Graig Fatha", "Kirk Hill", "Derril Water", "Whitelaw Brae"]`

you'll need to restart HA for it take affect

**Comment by shirehorse99** [comment]
that seems to work , Thanks for your help

Mark
