### ISSUE TITLE
Kirk Hill Wind Speed - MPH or m/s

### ISSUE THREAD

**Issue by Cameleon99** [ryanbdclark/ripple_energy#9]
Looking at the reported values in the integration, the wind speed looks incorrect. The API is reporting ~13 which is showing as 13MPH in HA, but on the Ripple dashboard its reporting 30MPH. This would equate to ~13m/s, so do we think the units on the API are actually m/s?

I've put a Tweet up to Ripple to see if they know for sure. - https://x.com/ChrisIngram_UK/status/1814337288337514898

**Comment by ryanbdclark** [comment]
The documentation states it’s in mph but what you are saying makes sense. Will see what they say

![image](https://github.com/user-attachments/assets/60549434-abb1-4bdb-9d4c-81f8106d6a7c)

**Comment by Cameleon99** [comment]
So it was an issue on Ripples side, they've now corrected it, confirmed the API value matches what the dashboard is showing. 

<img width="451" alt="image" src="https://github.com/user-attachments/assets/7cddd312-0c81-4816-b58f-56da4a9ea57f">

Just means history until the fix will be incorrect.

**Comment by ryanbdclark** [comment]
Thanks for confirming
